const unsigned char WebSide[] = {
"<!doctype html>"
"<html>"
"<head>"
"<meta charset=\"utf-8\">"
"<style type=\"text/css\">"
""
"html {"
"    width: 100%;"
"    height: 100%;"
"}"
""
"body {"
"    width: 100%;"
"    height: 100%;"
"    background-color: #1ABC9C;"
"font: 14px \"Lato\", sans-serif;"
"}"
""
"#container{"
"width:100%;"
"}"
""
"#table{"
"margin:25%;"
"background-color:#ECF0F1;"
"border-radius:8px;"
"}"
""
"input{"
"margin:5%;"
"font-size:30px;"
"color:#1ABC9C;"
"border-radius:8px;"
"border:groove;"
"}"
""
"#status{"
"background-color:#BDC3C7;"
"}"
""
"#chiudi{"
"width:20px;"
"height:20px;"
"background-color:#E74C3C;"
"border-color:#E74C3C;;"
"}"
""
"#chiudi:hover{"
"background-color:#C0392B;"
"border-color:# C0392B;"
"}"
""
"button{"
"margin:5%;"
"width:300px;"
"font-size:30px;"
"border-radius:10px;"
"color:#FFF;"
"font-size:center;"
"}"
""
"#button-invia{"
"border-color:#1ABC9C;"
"background:#1ABC9C;"
"}"
""
"#button-invia:hover{"
"background-color:#2fe2bf;"
"border-color:#2fe2bf;"
"}"
""
"#spazio{"
"width:50%;"
"height:50%;"
"}"
""
"#led{"
"width:100px;"
"height:100px;"
"background-color:#f1c40f;"
"text-align:center;"
"font-size:20px;"
"border-color:#f1c40f;"
"}"
""
"#led:hover{"
"background-color:#f39c12;"
"border-color:#f39c12;"
"}"
""
"#suono{"
"width:100px;"
"height:100px;"
"background-color:#3498DB;"
"text-align:center;"
"font-size:20px;"
"border-color:#3498DB;"
"}"
""
"#suono:hover{"
"background-color:#2980B9;"
"border-color:#2980B9;"
"}"
""
".text{"
"text-align:center;"
"margin-top:25px;"
"color:#34495e;"
"font-weight:bold;"
"}"
"  "
"</style>"
"<title>Controllo</title>"
"</head>"
"<body>"
"<div id=\"container\">"
"    "
"<div id=\"table\">"
"    <div id=\"status\">"
"    <button type=\"submit\" name=\"close\" id=\"chiudi\"></button></div>"
"    <form action=\"\" method=\"get\">"
"    <input type=\"text\" name=\"pw\" placeholder=\"password\">"
"        <button type=\"submit\" id=\"button-invia\" name=\"\">Invia</button>"
"</form>   "
"    </div>"
""
"<div id=\"table\">"
"<div id=\"status\">"
"    <button type=\"submit\" name=\"close\" id=\"chiudi\"></button>"
"    </div>"
"    "
"    <div id=\"spazio\">"
"    <div class=\"text\"> LED </div>"
"    <center>"
"    <button type=\"submit\" name=\"led\" id=\"led\">ON</button>"
"    </center>"
"    </div>"
"    "
"    <div id=\"spazio\">"
"    <div class=\"text\">SUOND</div>"
"    <center>"
"    <button id=\"suono\" name=\"sound\" type=\"submit\">ON</button>"
"    </center>"
"</div>"
"    "
"</div> <!-- container-->"
""
"</body>"
"</html>"
""
};
